title: UHC By Gwenzy
teamnumber: 4
maxplayers: 16
minpvp: 20
bordure:
  actual:
    center:
      x:
      z:
    size:
  retr:
    time:
    dist:
  minsize: 10
config:
  potion1: true
  potion2: false
  pommes: false
  timeperep: 20
timer:
  min: 20
  sec: 0
paused: false
